config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
  resources :items
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def new 
  end
  
  def index
    @items = Item.all
  end
  def show
      @item = Item.find(params[:id])
  end
    
  def create
    @item= Item.new(item_params)
    @item.save
      
    redirect_to @item
  end
  
  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    
    redirect_to @item
  end
  
  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_path
  end
  
  private
    def item_params
      params.require(:item).permit(:name, :price, :count)
    end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/edit.html.erb
<%= form_for :item, url: item_path(@item), method: :patch do |f| %>
<div class = "row">
	<div class= "row">
		<div class ="col-sm-4 col-md-4 col-xs-4"><%= f.label :name %></div>
		<div class ="col-sm-4 col-md-4 col-xs-4"><%= f.label :price %></div>
		<div class ="col-sm-4 col-md-4 col-xs-4"><%= f.label :count %></div>
	</div>
	
	<div class = "row">
		<div class ="col-sm-4 col-md-4 col-xs-4"><%= f.text_field :name %></div>
		<div class ="col-sm-4 col-md-4 col-xs-4"><%= f.text_field :price %></div>
		<div class ="col-sm-4 col-md-4 col-xs-4"><%= f.text_field :count %></div>
		
	</div>
	<br>
	<div class = "row text-center"> <%= f.submit %></div>
</div>
<% end %>

app/views/items/index.html.erb
<div class="row text-center"><h1>AVAILABLE ITEMS</h1></div>
<br>

<br>
<div class = "row">
    <div class = "col-xs-2 col-md-2 col-sm-2 text-center glyphicons glyphicons-imac"></div>
	<div class = "col-xs-1 col-md-1 col-sm-1"></div>
	<div class = "col-xs-2 col-md-2 col-sm-2">NAME</div>
	<div class = "col-xs-2 col-md-2 col-sm-2">PRICE</div>
	<div class = "col-xs-2 col-md-2 col-sm-2">COUNT</div>
	<div class = "col-xs-1 col-md-1 col-sm-1"></div>
	<div class = "col-xs-2 col-md-2 col-sm-2 text-center"></div>
	
</div>
<br>

<% @items.each do |item| %>
<div class = "row">
    <div class = "col-xs-2 col-md-2 col-sm-2 text-center"><%= link_to 'SHOW ITEM', item_path(item) %></div>
	<div class = "col-xs-1 col-md-1 col-sm-1">|</div>
	<div class = "col-xs-2 col-md-2 col-sm-2"><%= item.name %></div>
	<div class = "col-xs-2 col-md-2 col-sm-2"><%= item.price %></div>
	<div class = "col-xs-2 col-md-2 col-sm-2"><%= item.count %></div>
	<div class = "col-xs-1 col-md-1 col-sm-1">|</div>
	<div class = "col-xs-1 col-md-1 col-sm-1 text-center"><%= link_to 'EDIT ITEM', edit_item_path(item) %></div>
	<div class = "col-xs-1 col-md-1 col-sm-1 text-center"><%= link_to 'DELETE ITEM', item_path(item), method: :delete, data: { confirm: 'Are you sure?' } %></div>
	<hr>
</div>

<% end %>
<br>
<div class="row">
	<div class = " text-center"><%= link_to 'ADD NEW ITEM', new_item_path%></div>
	
</div>

app/views/items/new.html.erb
<%= form_for :item, url: items_path do |f| %>
<div class ="row">
	<div class= "row">
		<div class ="col-sm-4 col-xs-4"><%= f.label :NAME %></div>
		<div class ="col-sm-4 col-xs-4"><%= f.label :PRICE %></div>
		<div class ="col-sm-4 col-xs-4"><%= f.label :COUNT %></div>
	</div>
	
	<div class = "row">
		<div class ="col-sm-4 col-xs-4"><%= f.text_field :name %></div>
		<div class ="col-sm-4 col-xs-4"><%= f.text_field :price %></div>
		<div class ="col-sm-4 col-xs-4"><%= f.text_field :count %></div>
		
	</div>
	<br>
	<div class = "row text-center"> <%= f.submit %></div>
</div>
<% end %>

app/views/items/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>
<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>
<p>
  <strong>Count:</strong>
  <%= @item.count %>
</p>

<p>
	<%= link_to 'ALL ITEMS', items_path %>
</p>
<p><%= link_to 'EDIT ITEM', edit_item_path(@item)%></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Newblog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	  <div class ="container-fluid">
    <%= yield %>
</div>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>